### ISSUE TITLE
Crashes during Credits (Lon Lon Ranch)

### ISSUE THREAD

**Issue by 03bgood** [gamestabled/OoT3D_Randomizer#487] opened 2022-04-05 09:07 UTC
This happens right before it cuts to Malon singing. It then returns me to the 3DS home menu saying that an error has occurred.

I'm using v3.1, the latest nightly build has an issue where the it fails to generate a new seed after 5 attempts. This doesn't happen on the latest stable build, which is v3.1.

Update: Just beat it again, but this time it didn't crash. The credits played all the way through. So maybe there's a small chance it will crash.

**Comment by PhlexPlexico** [comment] 2024-08-02 15:05
Even though this is most likely the original, closing as is duplicate of #529.

Please refer to there when talking about crashing issues.
Thanks.

**Closed as not planned by PhlexPlexico** 2024-08-02 15:05 UTC
Labels: duplicate
